name: TownySpawnMenu
description: This plugin adds a browsable menu to teleport to other towns in Towny
author: Senkoco
main: me.senkoco.townyspawnmenu.Main
version: 1.2.4
api-version: 1.19
depend: [Towny]
commands:
  townyspawnmenu:
    description: Main command for usage of the plugin
    aliases: tsm